version: '3.8'
services:
  php:
    environment:
      DATABASE_URL: ${DATABASE_URL}
    build:
      dockerfile: docker/php/Dockerfile
    depends_on:
      - postgres
    ports:
      - "9090:9000"
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ~/.composer/composer.json:/home/root/.composer/composer.json
      - ~/.composer/.htaccess:/home/root/.composer/.htaccess
    networks:
      - phonebook
    extra_hosts:
      - "host.docker.internal:host-gateway"
  nginx:
    image: nginx:${NGINX_VERSION:-stable-alpine}
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - phonebook
  postgres:
    image: postgres:${POSTGRES_VERSION:-15}-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
    volumes:
      - database_data:/var/lib/postgresql/data:rw
    ports:
      - "5432:5432"
    networks:
      - phonebook

volumes:
  database_data:

networks:
  phonebook:
